### ISSUE TITLE
Using gravimetric water content and suction data for computing fitting variables

### ISSUE THREAD

**Issue by sarath4321iitb** [sekika/swrcfit#15]
Dear Sir, The software SWRC Fit your team developed is very helpful in obtaining SWRC fitting curve parameters. 
I am a geotechnical engineer doing research in the area of unsaturated soils where we capture data of gravimetric water content and suction. I understand that the software uses volumetric water content and suction values for computing the fitting variables. Can you please let me know how the code can be modified to use gravimetric water content data for computation of the fitting variables.
Thanking you in advance,
Regards
Sarath

**Comment by sekika** [comment]
Let
Mw = Water mass
Ms = Dry soil mass
Vw = Volume of water
V = Total volume
θ (Volumetric water content) = Vw / V
w (Gravimetric water content) = Mw / Ms
ρb (Bulk density) = Ms / V
ρw (Density of water) = Mw / Vw

Then it is easy to get the relationship of 
θ = w・ρb / ρw
When using the unit of g and cm, and using the value of ρw = 1g/cm3, 
θ = w・ρb

I think it is better to convert the data to θ this way, rather than modifying the code.

**Comment by sarath4321erpg** [comment]
Thanks for the prompt reply Sir.
