### ISSUE TITLE
Inf or NaN values & non-convergence errors

### ISSUE THREAD

**Issue by squasheds** [sekika/swrcfit#18]
Greetings, Dr. Seki. Thank you for making this tool available to everyone.

I've been running SWRC Fit on Windows 10 using Bash with this command "swrcfit /mnt/c/swrcfit-3.1/swrc.txt fx=0 ln=0 bc=0 precision=16" and have had trouble with a couple of my data sets. 

The first set is contains 2156 pairs, the first 552 of which are (0,###), the full set can be downloaded from [here](https://drive.google.com/file/d/1dU_So52v3yZjQJ8AKVDaVLJIprfuSEtR/view?usp=sharing). For this set I get the following error:

error: svd: cannot take SVD of matrix containing Inf or NaN values
error: called from
    __lm_svd__ at line 210 column 17
    leasqr at line 660 column 25
    /usr/local/bin/swrcfit at line 285 column 42

However, if I remove precisely the first 88 pairs of the set, I get this result instead:

=== VG model ===
qs =    2.739639883619983e-01
qr =    1.217364464164574e-06
alpha =  1.216654130630120
n =  1.153900954070656
R2 =    9.020961350393338e-01
warning: division by zero
warning: called from
    /usr/local/bin/swrcfit at line 491 column 21

I must eliminate the first 88 pairs or more and it only works if it's the first 88, eliminating any other pairs without eliminating the first 88 will yield the error. Why might this be happening and why might the threshold for the fit to work be the removal of precisely the first 88 pairs?

With my second set, downloadable [here](https://drive.google.com/file/d/1AKvha_P_g-l9zVknQFMK-QBvqsz4r2rq/view?usp=sharing), I get this non-convergence message. I do get values for the parameters of the VG model, but I don't know if I can use them, given the non-convergence. What would cause this and how could I get around it?

=== VG model ===
 CONVERGENCE NOT ACHIEVED!
qs =    3.688927052534632e-01
qr =    1.073886197142107e-05
alpha =    1.365121712845601e-01
n =  1.329595314249315
R2 =    9.665470577902827e-01
warning: division by zero
warning: called from
    /usr/local/bin/swrcfit at line 491 column 21

I thank you for your time and support.

**Comment by sekika** [comment]
For the first dataset:

After examining the calculation, I found that the reason is in the determination of the initial parameter of alpha in VG model in SWRC Fit. It is written in lines 274 to 276 as follows.

hm = x(sum(y > max(y)/2 + min(y)/2)+1);
if (hm==x(N)), hm=x(N-1); endif
alpha=1/hm; n=lambda+1;

This means that

(1) Calculate max(y)/2 + min(y)/2, the average of the minimum and maximum of theta. Call this value "medium of theta".
(2) Count how many of the data exceeds medium of theta. Add 1. Let this value m.
(3) Let mth dataset be (hm, theta_m). theta_m is expected to be smaller than medium of theta, and therefore it is safe to assume that hm is beyond air entry value.

In your dataset medium of theta is 0.244, m=436, hm=0, which caused the value of alpha to be infinity and the calculation failed. My assumption in (3) was not applicable to your data. In other words, I did not expect that such data would be used for calculation.

Maybe I can add a code where I increase the value of m until hm > 0 in the next release. Thank you for this feedback.
 
For the second dataset:
 	
 It is known that in some cases convergence is not achieved when the tolerance of the least square analysis is small. That is why in the code of lines 281 to 290, tolerance (stol) is gradually decreased. In the case of such error, the result where the convergence was achieved is displayed. Therefore, as long as you get the result, you can use that result. Ignore the message of convergence error.

**Comment by squasheds** [comment]
Dr. Seki, thank you for your reply.

I'll find a work around for my first data set and use the results given by SWRC for the second.
