### ISSUE TITLE
How to execute the program (swrcfit (SWRC Fit)  for  Large Data set fitting 

### ISSUE THREAD

**Issue by PhillRoss** [sekika/swrcfit#7]
Hi there !
It's a very useful program. I'am not that familiar with Cygwin. But comfortable with Gnu-plot. 
My questions :
1-) Is there a way to execute the fitting on N SWRC ? Because I am working with a large SWRC data set.
2-) Do you have an equivalent fortran program that does the fitting as *swrcfit* does ? 

Thank you in advance.

**Comment by sekika** [comment]
If you understand how the program works, you can make a program to execute a large number of  SWRC datasets by calling swrcfit, in whatever language you like. In your favorite language, do the following.

1) For each SWRC data, write the data in a single file as the specification of swrcfit.
2) Call swrcfit from the program. Use any command line options as you like. Output the result to the file by redirecting. For example, call swrcfit as "swrcfit filename > output".
3) Read the result and change to whichever format you like.

Actually the web interface is written in Perl and it is calling swrcfit. The source code is here.

https://github.com/sekika/swrcfit-cgi/blob/master/swrc.cgi

Please read these lines.

```
##### Calculation #####

# Here, swrcfit is called. setting.txt is automatically read and simple mode is selected.
# Therefore, the output parameter can directoly be stored to $result.
# Difference in the calculation option is specified by setting files.
# Error message from octave is discarded to /dev/null.
# Sometimes learsqr.m output message of "CONVERGENCE NOT ACHIEVED!".
# To supress this message, the output is piped to `grep -v "CON"`.

@result = `($swrcfit $fswrc $opt) 2> /dev/null | grep -v "CON"`;
```

It is actually reading the result directly to the array "@result". The mode "simple=1" is set in setting file.

Sometimes similar requests are given and therefore I once thought of making such a program. But actually for doing so, I will have to determine the specification of the "large number of dataset". In any case you will have to convert your data to that specification, and run the program. The problem is not getting any simple. Therefore I think the current status is enough.

**Comment by PhillRoss** [comment]
Thank you very much Sir.

I really appreciate your suggestions.

Sincerely yours

On Fri, Jul 1, 2016 at 7:21 PM, Katsutoshi Seki <notifications@github.com>
wrote:

> If you understand how the program works, you can make a program to execute
> a large number of SWRC datasets by calling swrcfit, in whatever language
> you like. In your favorite language, do the following.
>
> 1) For each SWRC data, write the data in a single file as the
> specification of swrcfit.
> 2) Call swrcfit from the program. Use any command line options as you
> like. Output the result to the file by redirecting. For example, call
> swrcfit as "swrcfit filename > output".
> 3) Read the result and change to whichever format you like.
>
> Actually the web interface is written in Perl and it is calling swrcfit.
> The source code is here.
>
> https://github.com/sekika/swrcfit-cgi/blob/master/swrc.cgi
>
> Please read these lines.
>
> ##### Calculation #####
>
> # Here, swrcfit is called. setting.txt is automatically read and simple mode is selected.
> # Therefore, the output parameter can directoly be stored to $result.
> # Difference in the calculation option is specified by setting files.
> # Error message from octave is discarded to /dev/null.
> # Sometimes learsqr.m output message of "CONVERGENCE NOT ACHIEVED!".
> # To supress this message, the output is piped to `grep -v "CON"`.
>
> @result = `($swrcfit $fswrc $opt) 2> /dev/null | grep -v "CON"`;
>
> It is actually reading the result directly to the array "@result
> <https://github.com/result>". The mode "simple=1" is set in setting file.
>
> Sometimes similar requests are given and therefore I once thought of
> making such a program. But actually for doing so, I will have to determine
> the specification of the "large number of dataset". In any case you will
> have to convert your data to that specification, and run the program. The
> problem is not getting any simple. Therefore I think the current status is
> enough.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/sekika/swrcfit/issues/7#issuecomment-229912665>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/ARn6IixgXZtpnomc2Ns-Dzrt8DuWs48Fks5qROo7gaJpZM4JC_Rk>
> .
>



-- 





*********************************************************************
*Magatt THIAM*
Tokyo University of Agriculture and Technology (TUAT)
United Graduate School of Agriculture
Agriculture and  Environmental Engineering Dept.
Environmental Geo-technique Lab.
------------------------------------------------------------------
*Personal address / Japanese*
〒 189-0012
東京都、東村山市
萩山町4丁目9番地12
高砂学生会館 301
------------------------------------------------------------------
*Personal address / English*
〒 189-0012
Tokyo, Higashimurayama-shi
 4-9-12 Hagiyama-cho
Takasago Student House 301

*********************************************************************
